### ISSUE TITLE
[BUG] Kernel crash when importing TimeGan in Jupiter

### ISSUE THREAD

**Issue by bishlarr** [ydataai/ydata-synthetic#62] opened 2021-04-27 09:28 UTC
Hi,

I would like to experiment Time Series Gan in Jupiter Notebook.
I pip installed the package, but when i try to import it the Kernel crash.
(from ydata_synthetic.synthesizers.timeseries import TimeGAN).

I am on a M1 Mac, supposed to be pretty powerful. Do you have any idea of the issue here?

Thanks for the good work !

**Comment by fabclmnt** [comment] 2021-04-27 10:16
Closing this @bishlarr  as this is not a bug. 

My recommendation is to use slack in order to try to understand what is going on.

**Closed by fabclmnt** 2021-04-27 10:16 UTC
Labels: bug
